FROM ubuntu:22.04

RUN apt update && apt install -y libc-bin

COPY passcode2 /home/noam/Desktop/pwnables/pwnable.kr/passcode/passcode2
COPY paylod /home/noam/Desktop/pwnables/pwnable.kr/passcode/paylod


CMD ["/bin/bash"]
